permalink: pretty
theme: jekyll_patternbot

patternbot:
  layouts:
    default: |
      This default layout should be used for almost every page, it include's the website's primary header and footer.
  title: Annika Designs
  font_url: "https://fonts.googleapis.com/css?family=Dosis|Lobster&display=swap"
  description: |
    Hello my name is Annika Cayanga.
    Growing up, my family and I moved places quite often. I ended up being exposed to many different cultures and that influenced my interest in the arts and design.
    Because I moved from country to country, the travel bug has stuck to me. Traveling has enabled me to explore new places and to get an insight on the beauty of different architectures, sculptures, and paintings.
    These inspired me to become the artist that I am today. I am still constantly exploring different aspects of design which helps me nurture my skills further.
    I enjoy bringing my camera and go pro on 8 hour hikes. You can catch me sipping on a good cup of vanilla latte while slurping on a delicious bowl of ramen. I would happily get paid in bowls of ramen or lattes!
  rationales:
    typefaces.primary: |
      Dosis font was selected as the primary typeface because of its consistent line thickness and height. This will allow users to browse though the website with ease because
      it is not too hard on the eyes.
    typefaces.secondary: |
      Lobster font was selected as the secondary typeface because of its gracefulness and touch of playfulness. With the clean curves and , this gives the font a refined
      touch which can relate to my style of design. This font is to be used mostly for headings due to its decorative character.
    colors.primary: |
      The primary colors selected are chosen. The darker green color is to be used for some headings and foreground to make the brand logo and content.
      The lighter green color will be used for some buttons to achieve continuity of the nature tones.
    colors.secondary: |
      The secondary color is a lighter and calmer green tone. To not overwhelm the eyes with just deep and bold greens, having a lighter green for the background will
      achieve a tranquil and calming effect to the website.
    colors.accent: |
      The accent colors selected will be used to achive consistency throughout the pages in the website. Using a different green tone slightly darker than the
      secondary will add more unity . The color white will be used to create a sense of space. White conveys feelings of freshness and simplicity
      which will complement the green colors well.
    colors.neutral: |
      The neutral color selected is more of an earthy beige tone which will continue the colors of nature.
  colors:
    background: "--color-primary"
    foreground: "--color-secondary"
    accent: "--color-secondary"
    patterns:
      brand.logos: "--color-secondary"

collections:
  products:
    output: true
defaults:
  - scope:
      path: _products
    values:
      layout: product
